### ISSUE TITLE
Add support for VPC functions.

### ISSUE THREAD

**Issue by smiller171** [LeafSoftware/python-lambder#2]

**Comment by chalfant** [comment]
Very timely. Was already working on this!

This commit should do the trick: https://github.com/LeafSoftware/python-lambder/commit/a4a0b97f786b4d13eb80e9b1112d71373e5563ba

Released as v1.2.1 to pypi.

Edit: I should also note that https://github.com/LeafSoftware/cookiecutter-lambder has also been updated to create a lambder.json with the subnet_ids and security_group_ids entries.
