### ISSUE TITLE
undocumented requirement to set a default boto region

### ISSUE THREAD

**Issue by smiller171** [LeafSoftware/python-lambder#3]
If I follow the instructions in the readme, I get the following error: `botocore.exceptions.NoRegionError: You must specify a region.`

I can solve this by running `export AWS_DEFAULT_REGION=us-east-1`

**Comment by chalfant** [comment]
Good catch. I'll add boto configuration to the README.

**Comment by chalfant** [comment]
Fixed in https://github.com/LeafSoftware/python-lambder/commit/fda9fafa563eba6c6937dfcb097d9bd5764dc564
